unit Unit3;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs,
  uWVWinControl,uWVWindowParent, uWVBrowserBase, uWVBrowser,
  uWVTypes, uWVConstants, uWVTypeLibrary,
  uWVLibFunctions, uWVLoader, uWVInterfaces, uWVCoreWebView2Args,
  uWVCoreWebView2SharedBuffer, Vcl.StdCtrls, System.IOUtils, Unit1, Vcl.ExtCtrls,System.RegularExpressions, System.NetEncoding;
type
  TForm3 = class(TForm)

    Button1: TButton;
    Button2: TButton;
    Button3: TButton;
    Button4: TButton;
    Button5: TButton;

    Panel1: TPanel;

    Timer1: TTimer;
    Timer2: TTimer;
    Timer3: TTimer;

    Memo1: TMemo;

    WVBrowser1: TWVBrowser;
    WVWindowParent1: TWVWindowParent;




        procedure WVBrowser1DOMContentLoaded(Sender: TObject;
      const aWebView: ICoreWebView2;
      const aArgs: ICoreWebView2DOMContentLoadedEventArgs);

          procedure WVBrowser1WebMessageReceived(Sender: TObject;
      const aWebView: ICoreWebView2;
      const aArgs: ICoreWebView2WebMessageReceivedEventArgs);


    procedure WVBrowser1AfterCreated(Sender: TObject);

    procedure FormCreate(Sender: TObject);
    procedure FormShow(Sender: TObject);


    procedure Button1Click(Sender: TObject);
    procedure Button2Click(Sender: TObject);
    procedure Button3Click(Sender: TObject);
    procedure Button4Click(Sender: TObject);
    procedure Button5Click(Sender: TObject);


    procedure ClickEngineManager;               // Javascript that notifies when TTS Engine is clicked
    procedure Delay(Milliseconds: Cardinal);    // Delay Procedure
    procedure ErrorMonitor;                     // Javascript that notifies when Tthere is a TTS error
    procedure GetTTStatus;                      // Javascript Monitors the PLayer State to Aquire status of TTS
    procedure GetVoices;                        // Javascript that sends all the TTS voice data ie name, real name, character limit
    procedure MyShow;                           // Handles Showing of form

    function PrepareStringForTTS(str: string): string;           // Try and clean up the TTS text
    function RemoveInternetTags(var InputString: string):string;  // Remove <Internet> tags and clean up the TTS text


    procedure SplitStringIntoSections(const StringToSplit: string; MaxLength: Integer; var templistofthingstosay: TStringlist); // Split the string up into appropriate sized chunks for the TTS Engine we are using

    procedure Timer1Timer(Sender: TObject);  // Load Browser
    procedure Timer2Timer(Sender: TObject);   // Error Dialog
    procedure Timer3Timer(Sender: TObject);   // If Splitting procedure Is being used but is called again wait and recheck to avoid interrupting up thingstosay stringlist order




  private
    { Private declarations }

     DialogueShown:Boolean;         // Prevented the dialog from showing multiple times in loading time out *** OLD WHEN USING WATSON TTS
     GotVoiceList : Boolean;        // We Load ALL the voices initially, once we've done that we don't have to keep reloading the list when TTS Engine changes
     IsSplitting : Boolean;         // Prevents the being calle dand interupting the order of the ListOfThingsToSay Stringlist
     LoadingVoiceTimeOut:Integer;   // LAZY PI HAS IT@S OWN TIME OUT ERROR THIS IS NOW DEFUNCT ?
                                    // **** DETECT THE SPINNING ICON IN BUTTON FOR ANIMATION AT LEAST ??
     NextStringToSplit : String;


    procedure WMMove(var aMessage : TWMMove); message WM_MOVE;
    procedure WMMoving(var aMessage : TMessage); message WM_MOVING;

  public
    { Public declarations }
       ReallyShow:Boolean;        // On Form Initialization
       ResubmitText : Boolean;    // After TTS Failed

       // These Stringlists Store the matching details by index for each voice in From1 combobox1
       RealNamesList: TStringList;
       ServiceList : TStringList;
       CharLimitList : Tstringlist;

       // String List to store appropriately split chunks for TTS that support different character limits
       ListofThingsToSay:TstringList;


       VoiceToUse:String;     // string to build TTS request URL
       ServiceToUse:String;   // string to build TTS request URL
       Retry:String;

       // Manage detection of different TTS Engine character limits
       TTSMaxLength:integer;
       OldTTSMaxLength: integer;

       procedure Speak(TextToSpeak:String);
       Procedure StopSpeaking;
       procedure ManageTTSList(new:string);
       procedure ClickVoiceManager;

  end;

var
  Form3: TForm3;


implementation

{$R *.dfm}



// The text generated by the AI may be too long for TTS engine, split it into segments.

procedure Tform3.SplitStringIntoSections(const StringToSplit: string; MaxLength: Integer; var templistofthingstosay: TStringlist);
var
  StartPos, EndPos, SectionEnd: Integer;
  CurrentSection, MyString: string;
begin

  Form1.Memo7.Lines.Add('In SplitStringIntoSections Form3' ) ;

 // Check if we're already splitting we need to prevent this being interuppted when the AI summerizes text from a webpage
  if IsSplitting then
  begin
   Form1.Memo7.Lines.Add('Already Splitting Using Timer To Wait' ) ;

    // Start the timer and exit
    NextStringToSplit := StringToSplit;
    Timer3.Enabled := True; // This timer should trigger every 2 seconds  and recall this procedure with the string NextStringToSplit
    Exit;
  end;

   Form1.Memo7.Lines.Add('Splitting It' ) ;

  // If not splitting, set the flag to true
  IsSplitting := True;
  MyString := StringToSplit;
  StartPos := 1;

while StartPos <= Length(MyString) do
begin
  // Determine the end of the current section based on the maximum length
  SectionEnd := StartPos + MaxLength - 1;
  if SectionEnd > Length(MyString) then
    SectionEnd := Length(MyString);

  // Try to find the last period (.), question mark (?), or exclamation mark (!) in the section to split
  EndPos := SectionEnd;
  while (EndPos > StartPos) and (not (MyString[EndPos] in ['.', '?', '!'])) do
    Dec(EndPos);

  // If no punctuation found, try to find the last space within the section
  if EndPos <= StartPos then
  begin
    EndPos := SectionEnd;
    while (EndPos > StartPos) and (MyString[EndPos] <> ' ') do
      Dec(EndPos);
  end;

  // If no space is found, split at the maximum length specified
  if EndPos <= StartPos then
    EndPos := SectionEnd;

    // Extract and add the current section to the list
    CurrentSection := Trim(Copy(MyString, StartPos, EndPos - StartPos + 1));
    ListOfThingsToSay.Add(CurrentSection);

    // Move start position to the next section
    StartPos := EndPos + 1;
  end;
     IsSplitting := False;
end;

//------------------------------------------------------------------------------

// Queue system for managing TTS outputs.
// This ensures smooth handling of multiple speech outputs. For example, if the we start to process
// "Ok, I will look on the internet <Internet><http://google.com/...></Internet> for TTS
// and then the summary response of the webpage, becomes ready to be processed for TTS beore the previous output has been processed,
// the summary would interrupt the previous output
// To prevent interruptions or overlaps, we need a queue system that allows us to store and manage these outputs.
// [PRELOADING]

//------------------------------------------------------------------------------

 procedure Tform3.ManageTTSList(new: string);
// Adds a new item to the list of things to say. If the TTS status is '[READY]',
// it will speak the  first item in the list. Otherwise, it just updates the list.
begin
  //Showmessage(Form1.TTStatus);

  // Add new item to the list if new item is not empty
  if Length(New) <> 0 then

  // Decide whether we need to split the text up because it's too long..
  Begin
   IF Length(New) < TTSMaxLength then   // We don't need to split it
   begin
   Form1.Memo7.Lines.Add('In ManageTTSList Form3') ;
   Form1.Memo7.Lines.Add('Less Than max length adding to ListOfThings To Say') ;
   Form1.Memo7.Lines.Add('MannageTTSist TTSStatus: ' + Form1.TTStatus ) ;
   ListofThingsToSay.add(new);
   end;

     IF Length(New) > TTSMaxLength then  // we need to split it
   begin
   Form1.Memo7.Lines.Add('In ManageTTSList Form3') ;
   Form1.Memo7.Lines.Add('More Than max length sending to SplitStringIntoSections') ;
   Form1.Memo7.Lines.Add('MannageTTSist TTSStatus: ' + Form1.TTStatus ) ;
   SplitStringIntoSections(new, TTSMaxLength, ListOfThingsToSay);
   Form1.Memo7.Lines.Add('splitting at:'+inttostr(TTSMaxLength));
   end;


  End;

  // Exit if the TTS system is not ready to speak
  if (Form1.TTStatus = '[LOADING]') or
     (Form1.TTStatus = '[SPEAKING]') or
     (Form1.TTStatus = '[PRELOADING]') then
    Exit;

  // If the TTS system is ready
  if Form1.TTStatus = '[READY]' then
  begin
    // If there are items to speak
    if ListofThingsToSay.Count > 0 then
    begin
      // Set status to '[PRELOADING]' to facilitate TTS queueing system
      Form1.TTStatus := '[PRELOADING]';


      // Speak the first item in the list
      Speak(ListofThingsToSay.Strings[0]);
      Retry := ListofThingsToSay.Strings[0];        // incase  we want to repeat the last attempted speech due to tts failure

      // Remove the first item that was just spoken
      if ListofThingsToSay.Count > 0 then
      ListofThingsToSay.Delete(0);
    end;
  end;
end;

//------------------------------------------------------------------------------
// Style Form Before Showing It

  procedure Tform3.MyShow;
  begin
  Self.BorderStyle := bsDialog;
  Form3.Width:=1405;
  Form3.Height:=650;
  Form3.Top := Form1.Top-20;
  Form3.Left := Form1.Left;
  Form3.ReallyShow := True;
  Form3.Show;
  WVWindowParent1.UpdateSize;
  end;

 //-----------------------------------------------------------------------------
// Stop TTS

  Procedure Tform3.StopSpeaking;
  var js:string;
  begin
        ListOfThingsToSay.Clear;

        js :=
        '// Select the audio element by its ID' + #13#10 +
        'var audioPlayer = document.getElementById(''audioplayer'');' + #13#10 +
        '' + #13#10 +
        '// Check if the audio player exists' + #13#10 +
        'if (audioPlayer) {' + #13#10 +
        '    // Stop the audio' + #13#10 +
        '    audioPlayer.pause().catch(function(error) {' + #13#10 +
        '        console.error(''Error attempting to stop audio:'', error);' + #13#10 +
        '    });' + #13#10 +
       '} else {' + #13#10 +
        '    console.log(''Audio player not found.'');' + #13#10 +
        '}';
    if Assigned(WVBrowser1) then  WVBrowser1.ExecuteScript(js);
  end;

//------------------------------------------------------------------------------
// Removes Characters that aren't conducive to TTS

function Tform3.PrepareStringForTTS(str: string): string;
var
temp:string;
begin

  // Replace all types of line breaks with a space
  Result := StringReplace(str, #13#10, ' ', [rfReplaceAll]);
  Delay(10);
  Result := StringReplace(Result, #10, ' ', [rfReplaceAll]);
  Delay(10);
  Result := StringReplace(Result, #13, ' ', [rfReplaceAll]);
  Delay(10);
  // Replace tabs and other spaces with a single space
  Result := StringReplace(Result, #9, ' ', [rfReplaceAll]);  // Replace tabs
   Delay(10);
  Result := StringReplace(Result, '  ', ' ', [rfReplaceAll]);  // Multiple spaces
  Delay(10);
  // Handle unwanted characters or symbols
  Result := StringReplace(Result, '-', ' ', [rfReplaceAll]);   // Replace dashes with space
  Delay(10);
  Result := StringReplace(Result, ' .', '.', [rfReplaceAll]);  // Remove space before dot
   Delay(10);
  Result := StringReplace(Result, ',', ', ', [rfReplaceAll]);  // Ensure space after commas
   Delay(10);
  Result := StringReplace(Result, '!', '! ', [rfReplaceAll]);  // Ensure space after exclamation marks
   Delay(10);
  Result := StringReplace(Result, '?', '? ', [rfReplaceAll]);  // Ensure space after question marks
   Delay(10);
     Result := StringReplace(Result, '*', ' ', [rfReplaceAll]);
   Delay(10);
        Result := StringReplace(Result, '- ', '.', [rfReplaceAll]);
   Delay(10);
           Result := StringReplace(Result, ' -', '.', [rfReplaceAll]);
   Delay(10);
              Result := StringReplace(Result, ' - ', '.', [rfReplaceAll]);
   Delay(10);

  // Trim leading and trailing spaces
  Result := Trim(Result);
   Delay(10);
  // Additional cleanup: remove any redundant spaces introduced
  while Pos('  ', Result) > 0 do

  Result := StringReplace(Result, '  ', ' ', [rfReplaceAll]);  // Ensure single spaces
  // Replace all occurrences of double quotes with a space
   Delay(10);
  Result := StringReplace(Result, '"', ' ', [rfReplaceAll]);

end;

//------------------------------------------------------------------------------
// Remove Any Internet Tags for TTS

function Tform3.RemoveInternetTags(var InputString: string):string;
var
  Regex: TRegEx;
begin
  // Define the regular expression to match <Internet>...</Internet>
  Regex := TRegEx.Create('<Internet>.*?</Internet>', [roSingleLine]);
  Result := Regex.Replace(InputString, '');
end;

//------------------------------------------------------------------------------
//Delay Function

procedure Tform3.Delay(Milliseconds: Cardinal);
var
  StartTickCount: Cardinal;
begin
  StartTickCount := GetTickCount;
  while (GetTickCount - StartTickCount) < Milliseconds do
  begin
  end;
end;

//------------------------------------------------------------------------------

//  DELETE THIS ************** Run Javascript In Memo1
procedure TForm3.Button1Click(Sender: TObject);
var
  jsCode: string;
begin
    if Assigned(WVBrowser1) then  WVBrowser1.ExecuteScript(Memo1.text);
end;
// Delet this **********  Speak The Text In Memo1
procedure TForm3.Button3Click(Sender: TObject);
begin
Form1.TTStatus := '[READY]';
ManageTTSList(Memo1.text);
end;
// Delet this **********
procedure TForm3.Button5Click(Sender: TObject);
begin

 Showmessage(Form1.TTStatus);
end;

//------------------------------------------------------------------------------
// Close Form

 procedure TForm3.Button2Click(Sender: TObject);
 begin
 Form3.Close;
 end;

//------------------------------------------------------------------------------
// Refresh TTS webpage

 procedure TForm3.Button4Click(Sender: TObject);
 var
 url:string;
begin
  WVWindowParent1.UpdateSize;
 url:= 'https://lazypy.ro/tts/?lang=All&g=A';
  WVBrowser1.Navigate(url);
  WVWindowParent1.UpdateSize;
end;

//------------------------------------------------------------------------------
// Read Messages From WebPage To Determine TTS State

procedure TForm3.WVBrowser1WebMessageReceived(Sender: TObject; const aWebView: ICoreWebView2; const aArgs: ICoreWebView2WebMessageReceivedEventArgs);
var
  TempArgs: TCoreWebView2WebMessageReceivedEventArgs;
  MessageData: string;
  UserResponse: Integer;
  I, ItemIndex:integer;
  MainParts: TArray<string>;
  NameParts: TArray<string>;
  LimitParts: TArray<string>;
  Sets: TArray<string>;

begin
  TempArgs := TCoreWebView2WebMessageReceivedEventArgs.Create(aArgs);

  // Retrieve message data from web message
  MessageData := TempArgs.WebMessageAsString;


  // Handle Messages from browser re TTS Status

        if Pos('[ERROR]', MessageData)>0 then
  begin
  Delete(MessageData, 1, 7);
  Timer2.Enabled:=True;
  //ShowMessage(MessageData);
  end;

        if Pos('[VOICESELECTED]', MessageData)>0 then
    begin
        Delete(MessageData, 1, 15);
        // Find the index of the item that matches MessageData
        ItemIndex := Form1.ComboBox1.Items.IndexOf(trim(MessageData));

        //Showmessage(MessageData);

        // If the item is found, set it as the selected item
        if ItemIndex <> -1 then Form1.ComboBox1.ItemIndex := ItemIndex;
        Form1.ComboBox1.OnChange(Form1.ComboBox1);
    end;


     // If user selects new TTS Engine, trigger the update of the combox with the new voices
      if Pos('[UPDATEVOICES]', MessageData)>0 then
  begin
  Delete(MessageData, 1, 14);
  Form1.ComboBox1.Clear;
  GetVoices; // This executes the javascript that will send the list of voices preceded by [VOICES]
  end;

    // Browser Is sending a List of voices for the combobox
    if Pos('[VOICES]', MessageData)>0 then
  begin
  MessageData := StringReplace(MessageData, '[VOICES]', '', [rfReplaceAll]);

  // Delete this junk from the start of the string
  MessageData := StringReplace(MessageData, '!!null**null$$', '', [rfReplaceAll]);
  //Inbetween nul$$ <HERE> !! could be any TTS Engine Name So We Delete to the start of the next Parse Position Identifier
  Delete(MessageData, 1, Pos('!!', MessageData) -1 );

    // Form1.Memo3.Lines.Add(MessageData);

// Clear the ComboBox and RealNamesList and servicelist before adding new items
Form1.ComboBox1.Clear;
RealNamesList.Clear;  // the voice name we include in the url to generate th TTS voice
ServiceList.Clear;    // the service we include in the url to generate voice (The TTS Engine we are using)
CharLimitList.Clear;  // where we store the character limit for each voice

// First split by !! to get each complete set
Sets := MessageData.Split(['!!']);

// Process each set
for i := 1 to Length(Sets) - 1 do  // Start from 1 as first split will be empty due to leading !!
begin
    // Now split each set by $$ to separate service
    MainParts := Sets[i].Split(['$$']);
    if Length(MainParts) = 2 then
    begin
        // Split the first part by ** to get display name and real name
        NameParts := MainParts[0].Split(['**']);
        // Now split the second part by ££ to get service and char limit
        LimitParts := MainParts[1].Split(['££']);

        if Length(NameParts) = 2 then
        begin
            Form1.ComboBox1.Items.Add(NameParts[0]);   // Display name
            RealNamesList.Add(NameParts[1]);           // Real name
            ServiceList.Add(LimitParts[0]);            // Service

            if Length(LimitParts) = 2 then
            begin
                CharLimitList.Add(LimitParts[1]);      // CharLimit
            end
            else
            begin
                CharLimitList.Add('100'); // err on the side of caution
            end;
        end;
    end;
end;

    // Set the selected index to the first item
    if  Form1.ComboBox1.Items.Count > 0 then Form1.ComboBox1.ItemIndex := 0;
    Form1.ComboBox1.OnChange(Form1.ComboBox1);
    GotVoiceList := True; // Set the flag

    // Now We have the voices lets load the saved voice and other saved settings
    Form1.LoadSettings;

 end;


  if Pos('[READY]', MessageData)>0 then
  begin
      if Form1.TTStatus = '[PRELOADING]' then  Exit; // Stops summerize request jumping the TTS queue
      LoadingVoiceTimeOut:=0;
    //  Form1.Memo3.Lines.add('[READY]');


       if Not Form1.CheckBox4.Checked then  // only change to black when developpin it kept flashing and bugging me
      Begin

      // Stactic black TTS Image
      Form1.Image5.Visible := True;
      // Stactic Green TTS Image
      Form1.Image6.Visible := False;
      // Animated Loading Image
      Form1.Image7.Visible := False;
      // Animated Speaking Image
      Form1.Image8.Visible := False;
      end;


      if Form1.CheckBox4.Checked then  // only change to the static green tts image if we are in tts mode otherwise leave it black
      Begin

      // Stactic black TTS Image
      Form1.Image5.Visible := False;
      // Stactic Green TTS Image
      Form1.Image6.Visible := True;
      // Animated Loading Image
      Form1.Image7.Visible := False;
      // Animated Speaking Image
      Form1.Image8.Visible := False;


      // If the Stauts changes from [SPEAKING] to [READY] and there is more AI Output to send to the TTS
      // This occurs after an ouput such as "ok i will look on the internet <Internet><http://google.com...</Internet>"
      // The tts starts saying "Ok i will look..." , The response from the AI to summerize the scraped google text can interrupt
      // previous output, So we implement aqueue system for the TTS

       if Form1.TTStatus = '[SPEAKING]' then
            // Here we know the TTS Stopped Speaking and Is Ready For Next Input, if there are multiple things on List
          begin
        //  Showmessage('Stopped Speaking setting to ready');
          Form1.TTStatus := '[READY]';


            if ListofThingsToSay.Count > 0 then
            Begin
            ManageTTSList('');  // Sending an empty string will result in the next AI output on the list being sent to TTS
            end;

          end;

      End;

    Form1.TTStatus := '[READY]';

  end; // end of if Pos('[READY]'



  if Pos('[LOADING]',MessageData)>0 then
  begin
   //    if (Form1.TTStatus <> '[PRELOADING]') or (Form1.TTStatus <> '[LOADING]') then Exit; //.. Stops animation when user clicks play in tts window


      //ShowMessage('[LOADING]');
      Form1.TTStatus := '[LOADING]';
      //Form1.Memo3.Lines.add('[LOADING]');
      Inc(LoadingVoiceTimeOut);
      // Stactic black TTS Image
      Form1.Image5.Visible := False;
      // Stactic Green TTS Image
      Form1.Image6.Visible := False;
      // Animated Loading Image
      Form1.Image7.Visible := True;
      // Animated Speaking Image
      Form1.Image8.Visible := False;


      // If Voice has been loading for too long time out
      if LoadingVoiceTimeOut>150 then
      begin
       LoadingVoiceTimeOut:=0;
       WVBrowser1.ExecuteScript('intervalController.stop();');
       Timer2.Enabled:=True;
      end; // end of if LoadingVoiceTimeout>150

    end; // end of if pos [LOADING]>0


  if Pos('[SPEAKING]',MessageData)>0 then
  begin
  LoadingVoiceTimeOut:=0;
      //  ShowMessage('[SPEAKING]');
      Form1.TTStatus := '[SPEAKING]';
      //Form1.Memo3.Lines.add('[SPEAKING]');
      // Stactic Black TTS Image
      Form1.Image5.Visible := False;
      // Stactic Green TTS Image
      Form1.Image6.Visible := False;
      // Animated Loading Image
      Form1.Image7.Visible := False;
      // Animated Speaking Image
      Form1.Image8.Visible := True;
  end


end;

//------------------------------------------------------------------------------
                          // SPEAK
//------------------------------------------------------------------------------
// Send Text Chunk To TTS Engine

procedure TForm3.Speak(TextToSpeak:String);
  var
  js:string;


  begin
  Form1.Memo7.Lines.Add('Max Characters for voice: '+inttostr(TTSMaxLength));
  Form1.Button3.Visible := False; // hide The Retry Text To Speech Button
  TextToSpeak := RemoveInternetTags(TextToSpeak);
  // Try and Clean what the AI said so it is appropriate for TTS
  TextToSpeak := PrepareStringForTTS(TextToSpeak);

  //Form1.Memo3.Text := (TextToSpeak);

  if length(trim(TextToSpeak))<3 then
  begin
  Form1.TTStatus := '[READY]';
  exit;
  end;


  TextToSpeak := TNetEncoding.URL.Encode(TextToSpeak);

  WVWindowParent1.UpdateSize;
  WVBrowser1.Navigate('https://lazypy.ro/tts/?voice='+VoiceToUse+'&service='+ServiceToUse+'&text=' + TextToSpeak);
  WVWindowParent1.UpdateSize;

  // Place the text in the webpage's textarea for user aesthetics
  js:=
      'var textArea = document.getElementById("text");' + #13#10 +
      'var playButton = document.getElementById("btn");' + #13#10 +
      'if (textArea) {' + #13#10 +
      'textArea.value = "' + TextToSpeak + '";' + #13#10 +
      'var inputEvent = new Event(''input'', { bubbles: true });' + #13#10 +
      'var changeEvent = new Event(''change'', { bubbles: true });' + #13#10 +
      'textArea.dispatchEvent(inputEvent);' + #13#10 +
      'textArea.dispatchEvent(changeEvent);' + #13#10 +
      '}';

   if Assigned(WVBrowser1) then  WVBrowser1.ExecuteScript(js);

   // Run Javascript that monitors tts status
   GetTTStatus;

   end;

//------------------------------------------------------------------------------
// Get List Of Voices Or Speak Text

  procedure TForm3.WVBrowser1DOMContentLoaded(Sender: TObject;
  const aWebView: ICoreWebView2;
  const aArgs: ICoreWebView2DOMContentLoadedEventArgs);
  var js:String;
  begin

  //Aesthetics
 js := 'var tabContainer = document.getElementById(''tab-container'');' + #13#10 +
        '' + #13#10 +
        'if (tabContainer) {' + #13#10 +
        '    tabContainer.style.display = ''none'';' + #13#10 +
        '}' + #13#10 +
        '' + #13#10 +
        'var titleElement = document.querySelector(''h1.title.is-2'');' + #13#10 +
        '' + #13#10 +
        'if (titleElement) {' + #13#10 +
        '    titleElement.textContent = ''Text To Speech for LM Studio'';' + #13#10 +
        '}' + #13#10 +
        '' + #13#10 +
        'var voiceCountElement = document.getElementById(''voicecount'');' + #13#10 +
        'var subtitleElement = document.querySelector(''p.subtitle.is-4'');' + #13#10 +
        '' + #13#10 +
        'if (voiceCountElement && subtitleElement) {' + #13#10 +
        '    // Extract the text content from the span, which is the number of voices' + #13#10 +
        '    var voiceCount = voiceCountElement.textContent.trim();' + #13#10 +
        '' + #13#10 +
        '    subtitleElement.innerHTML = `${voiceCount} voices thanks to <a href="https://lazypy.ro/tts/" target="_blank">LazyPy</a>`;' + #13#10 +
        '}' + #13#10 +
        '' + #13#10 +
        'var paragraphs = document.querySelectorAll(''p:not(.subtitle)'');' + #13#10 +
        '' + #13#10 +
        '// Loop through each selected <p> element and hide it' + #13#10 +
        'paragraphs.forEach(function(paragraph) {' + #13#10 +
        '    paragraph.style.display = ''none'';' + #13#10 +
        '});' + #13#10 +

       // Click Play To play the TTS if loaded
        '// Select the audio element by its ID' + #13#10 +
        'var audioPlayer = document.getElementById(''audioplayer'');' + #13#10 +
        '' + #13#10 +
        '// Check if the audio player exists' + #13#10 +
        'if (audioPlayer) {' + #13#10 +
        '    // Play the audio' + #13#10 +
        '    audioPlayer.play().catch(function(error) {' + #13#10 +
        '        console.error(''Error attempting to play audio:'', error);' + #13#10 +
        '    });' + #13#10 +
        '} else {' + #13#10 +
        '    console.log(''Audio player not found.'');' + #13#10 +
        '}'+ #13#10 +

        // get number of voices

                'if (voiceCountElement && subtitleElement) {' + #13#10 +
        '    // Extract the text content from the span, which is the number of voices' + #13#10 +
        '    var voiceCount = voiceCountElement.textContent.trim();' + #13#10 +
        '' + #13#10 +
        '    subtitleElement.innerHTML = `${voiceCount} voices thanks to <a href="https://lazypy.ro/tts/" target="_blank">LazyPy</a>`;' + #13#10 +
        '}'   ;

     if Assigned(WVBrowser1) then  WVBrowser1.ExecuteScript(js);

     if not GotVoiceList    then
     begin
       Delay(1000);
       GetVoices;            // Get List of Voices From Browser
       end;

       Delay(1000);
       GetTTStatus;            // Detect STatus of Voice Player In Browser
       Delay(1000);
       ClickEngineManager;     // Detect TTS Engine Change In Browser
       Delay(1000);
       ClickVoiceManager;      // Detect TTS Voice Change In Browser


       // If there's an error give the user the option to retry TTS
       if ResubmitText = True then
       begin
       ResubmitText := False;
       Form1.TTStatus := '[PRELOADING]';
       Speak(Retry);

       end;

end;

//------------------------------------------------------------------------------
// Detect When A Voice Is selected in the Browser and Send Message To Change Form1 Combobox

procedure TForm3.ClickVoiceManager;
var
  js: string;
begin

begin
js :=
  'var buttons = document.querySelectorAll("button");' + #13#10 +
  '// Add click event listener to each button' + #13#10 +
  'buttons.forEach(function(button) {' + #13#10 +
  '    button.addEventListener("click", function() {' + #13#10 +
  '        // Get the title attribute of the clicked button' + #13#10 +
  '        var buttonTitle = button.getAttribute("title");' + #13#10 +
  '        // Show an alert with the button''s title' + #13#10 +
 // '        alert("Button title: " + buttonTitle);' + sLineBreak +
  '        // Conditional statement to send a message if chrome.webview is available' + #13#10 +
  '        if (window.chrome && window.chrome.webview && typeof window.chrome.webview.postMessage === "function") {' + #13#10 +
  '            window.chrome.webview.postMessage("[VOICESELECTED]" + buttonTitle); // Send the result data with "[VOICESELECTED]" prefix' + #13#10 +
  '            console.log("Button clicked: " + buttonTitle); // Log the result' + #13#10 +
  '        } else {' + #13#10 +
  '            console.log("window.chrome.webview.postMessage is not available."); // Log if not available' + #13#10 +
  '        }' + #13#10 +
  '    });' + #13#10 +
  '});';
end;

  if Assigned(WVBrowser1) then  WVBrowser1.ExecuteScript(js);
end;

//------------------------------------------------------------------------------
// Detect Errors from TTS Webpage

 procedure TForm3.ErrorMonitor;
var
  js: string;

begin
  js := '// Initial state to track the visibility of the div' + #13#10 +
        'var isDivVisible = false;' + #13#10 +
        '' + #13#10 +
        '// Function to check if the div is visible or hidden' + #13#10 +
        'function checkDivVisibility() {' + #13#10 +
        '    var divElement = document.getElementById(''tts-error-text'');' + #13#10 +
        '' + #13#10 +
        '    if (divElement) {' + #13#10 +
        '        // Check if the div is visible (display is not ''none'' and it''s not detached)' + #13#10 +
        '        var isCurrentlyVisible = divElement.offsetParent !== null;' + #13#10 +
        '' + #13#10 +
        '        // If visibility has changed to visible' + #13#10 +
        '        if (isCurrentlyVisible && !isDivVisible) {' + #13#10 +
        '            // Get the text content from the div' + #13#10 +
        '            var textFromDiv = divElement.textContent || divElement.innerText;' + #13#10 +
        '' + #13#10 +
        '            // Send a message using window.chrome.webview.postMessage if available' + #13#10 +
        '            if (window.chrome && window.chrome.webview && typeof window.chrome.webview.postMessage === ''function'') {' + #13#10 +
        '                window.chrome.webview.postMessage(''[ERROR]'' + textFromDiv); // Send the result data with "[ERROR]" prefix' + #13#10 +
        '                console.log(`Message sent to webview: ${textFromDiv}`); // Log the sent message' + #13#10 +
        '            } else {' + #13#10 +
        '                console.log(''window.chrome.webview.postMessage is not available.''); // Log if not available' + #13#10 +
        '            }' + #13#10 +
        '' + #13#10 +
        '            // Update the state to reflect that the div is now visible' + #13#10 +
        '            isDivVisible = true;' + #13#10 +
        '        }' + #13#10 +
        '        // If visibility has changed to hidden' + #13#10 +
        '        else if (!isCurrentlyVisible && isDivVisible) {' + #13#10 +
        '            isDivVisible = false;' + #13#10 +
        '        }' + #13#10 +
        '    }' + #13#10 +
        '}' + #13#10 +
        '' + #13#10 +
        '// Create a MutationObserver to monitor changes in the DOM' + #13#10 +
        'var observer = new MutationObserver(function(mutations) {' + #13#10 +
        '    mutations.forEach(function(mutation) {' + #13#10 +
        '        // Check the visibility status on each mutation' + #13#10 +
        '        checkDivVisibility();' + #13#10 +
        '    });' + #13#10 +
        '});' + #13#10 +
        '' + #13#10 +
        '// Start observing the body for changes in the entire document and attributes' + #13#10 +
        'observer.observe(document.body, { childList: true, subtree: true, attributes: true });' + #13#10 +
        '' + #13#10 +
        '// Initial check in case the div is already visible when the page loads' + #13#10 +
        'checkDivVisibility();';

       if Assigned(WVBrowser1) then  WVBrowser1.ExecuteScript(js);
end;

//------------------------------------------------------------------------------
// Sends Updated Voice List When User Clicks On A Tab

procedure TForm3.ClickEngineManager;
var
  js: string;
begin
  js := 'var tabs = document.querySelectorAll(''.tab'');' + #13#10 +
        '' + #13#10 +
        '// Add click event listener to each tab' + #13#10 +
        'tabs.forEach(tab => {' + #13#10 +
        '    tab.addEventListener(''click'', () => {' + #13#10 +
        '        // Get the text of the clicked tab' + #13#10 +
        '        const tabName = tab.querySelector(''a'').textContent;' + #13#10 +
        '' + #13#10 +
        '        // Show an alert with the tab name' + #13#10 +
        '        // alert(`You clicked on: ${tabName}`);' + #13#10 +
'// Select the button using its data-lang attribute value "All"' + #13#10 +
      'var langButton = document.querySelector(''button[data-lang="All"]'');' + #13#10 +
      '' + #13#10 +
      '// Check if the button exists and click it' + #13#10 +
      'if (langButton) {' + #13#10 +
      '    langButton.click();' + #13#10 +
      '' + #13#10 +
      '    // Wait for 1 second before executing the rest of the code' + #13#10 +
      '    setTimeout(function() {' + #13#10 +
      '' + #13#10 +
      '        // Conditional statement to send a message if the chrome.webview is available' + #13#10 +
      '        if (window.chrome && window.chrome.webview && typeof window.chrome.webview.postMessage === ''function'') {' + #13#10 +
      '            window.chrome.webview.postMessage(`[UPDATEVOICES]${tabName}`); // Send the result data with "[UPDATEVOICES]" prefix' + #13#10 +
      '            console.log(`Tab clicked: ${tabName}`); // Log the result' + #13#10 +
      '        } else {' + #13#10 +
      '            console.log(''window.chrome.webview.postMessage is not available.''); // Log if not available' + #13#10 +
      '        }' + #13#10 +
      '    }, 1000);' + #13#10 +
      '} else {' + #13#10 +
      '    console.log(''Button with data-lang="All" not found.'');' + #13#10 +
      '}' ;

         if Assigned(WVBrowser1) then  WVBrowser1.ExecuteScript(js);

end;

//------------------------------------------------------------------------------
//NewTTS

procedure TForm3.GetVoices;
var js:String;
begin

  js := 'var tabContainer = document.getElementById(''tab-container'');' + #13#10 +
        '' + #13#10 +
        'if (tabContainer) {' + #13#10 +
        '    tabContainer.style.display = ''none'';' + #13#10 +
        '}' + #13#10 +
        '' + #13#10 +
        'var titleElement = document.querySelector(''h1.title.is-2'');' + #13#10 +
        '' + #13#10 +
        'if (titleElement) {' + #13#10 +
        '    titleElement.textContent = ''Text To Speech for LM Studio'';' + #13#10 +
        '}' + #13#10 +
        '' + #13#10 +
        'var voiceCountElement = document.getElementById(''voicecount'');' + #13#10 +
        'var subtitleElement = document.querySelector(''p.subtitle.is-4'');' + #13#10 +
        '' + #13#10 +
        'if (voiceCountElement && subtitleElement) {' + #13#10 +
        '    // Extract the text content from the span, which is the number of voices' + #13#10 +
        '    var voiceCount = voiceCountElement.textContent.trim();' + #13#10 +
        '' + #13#10 +
        '    subtitleElement.innerHTML = `${voiceCount} voices thanks to <a href="https://lazypy.ro/tts/" target="_blank">LazyPy</a>`;' + #13#10 +
        '}' + #13#10 +
        '' + #13#10 +
        'var paragraphs = document.querySelectorAll(''p:not(.subtitle)'');' + #13#10 +
        '' + #13#10 +
        '// Loop through each selected <p> element and hide it' + #13#10 +
        'paragraphs.forEach(function(paragraph) {' + #13#10 +
        '    paragraph.style.display = ''none'';' + #13#10 +
        '});' + #13#10 +
      '' + #13#10 +
      '// Select all button elements with the class "button-voice"' + #13#10 +
  'var buttons = Array.from(document.querySelectorAll(''.button-voice''))' + #13#10 +
  '.filter(button => {' + #13#10 +
    'return button.offsetWidth > 0 && button.offsetHeight > 0 && getComputedStyle(button).visibility !== ''hidden'';' + #13#10 +
  '});' + #13#10 +
      '' + #13#10 +
      '// Extract title and data-vid values, then join them with a comma between pairs' + #13#10 +
      'var result = Array.from(buttons)' + #13#10 +
      '  .map(function(button) {' + #13#10 +
  'return ''!!'' + button.getAttribute(''title'') + ''**'' + button.getAttribute(''data-vid'') + ''$$'' + button.getAttribute(''data-api'') + ''££'' + button.getAttribute(''data-charlimit'');' + #13#10 +
      '  })' + #13#10 +
      '  .join(''''); // Join pairs with a **' + #13#10 +
      '' + #13#10 +
      '// Check if the postMessage function is available and send the data' + #13#10 +
      'if (window.chrome && window.chrome.webview && typeof window.chrome.webview.postMessage === ''function'') {' + #13#10 +
      '    window.chrome.webview.postMessage("[VOICES]" + result); // Send the result data with "[VOICES]" prefix' + #13#10 +
      '    console.log(result); // Log the result' + #13#10 +
      '} else {' + #13#10 +
      '    console.log(''window.chrome.webview.postMessage is not available.''); // Log if not available' + #13#10 +
      '}';

      if Assigned(WVBrowser1) then  WVBrowser1.ExecuteScript(js);
end;

//------------------------------------------------------------------------------
// Checks the TTS Play Button To Find The State Of TTS Then Sends The Relevent Message For Us To Handle The Event

  procedure TForm3.GetTTStatus;
  var js:String;
  begin

  js :=
    'var sharedController = {' + #13#10 +
    '    isDivVisible: false,' + #13#10 +
    '    lastMessage: null,' + #13#10 +
    '    sendMessage: function(message) {' + #13#10 +
    '        if (message !== this.lastMessage) {' + #13#10 +
    '            if (window.chrome && window.chrome.webview && typeof window.chrome.webview.postMessage === ''function'') {' + #13#10 +
    '                window.chrome.webview.postMessage(message);' + #13#10 +
    '                this.lastMessage = message;' + #13#10 +
    '                console.log(`Message sent: ${message}`);' + #13#10 +
    '            } else {' + #13#10 +
    '                console.log(''window.chrome.webview.postMessage is not available.'');' + #13#10 +
    '            }' + #13#10 +
    '        }' + #13#10 +
    '    }' + #13#10 +
    '};' + #13#10 +
    '' + #13#10 +
    '// JS1 Modifications' + #13#10 +
    'function checkDivVisibility() {' + #13#10 +
    '    var divElement = document.getElementById(''tts-error-text'');' + #13#10 +
    '    if (divElement) {' + #13#10 +
    '        var isCurrentlyVisible = divElement.offsetParent !== null;' + #13#10 +
    '        if (isCurrentlyVisible && !sharedController.isDivVisible) {' + #13#10 +
    '            var textFromDiv = divElement.textContent || divElement.innerText;' + #13#10 +
    '            sharedController.sendMessage(''[ERROR]'' + textFromDiv);' + #13#10 +
    '            sharedController.isDivVisible = true;' + #13#10 +
    '        } else if (!isCurrentlyVisible && sharedController.isDivVisible) {' + #13#10 +
    '            sharedController.isDivVisible = false;' + #13#10 +
    '        }' + #13#10 +
    '    }' + #13#10 +
    '}' + #13#10 +
    '' + #13#10 +
    'var observer = new MutationObserver(function(mutations) {' + #13#10 +
    '    mutations.forEach(function() {' + #13#10 +
    '        checkDivVisibility();' + #13#10 +
    '    });' + #13#10 +
    '});' + #13#10 +
    '' + #13#10 +
    'observer.observe(document.body, { childList: true, subtree: true, attributes: true });' + #13#10 +
    'checkDivVisibility(); // Initial check' + #13#10 +
    '' + #13#10 +
    '// JS2 Modifications' + #13#10 +
    'var intervalController = {' + #13#10 +
    '    intervalId: null,' + #13#10 +
    '    start: function() {' + #13#10 +
    '        if (this.intervalId === null) {' + #13#10 +
    '            this.intervalId = setInterval(this.checkForElements.bind(this), 250);' + #13#10 +
    '        }' + #13#10 +
    '    },' + #13#10 +
    '    stop: function() {' + #13#10 +
    '        if (this.intervalId !== null) {' + #13#10 +
    '            clearInterval(this.intervalId);' + #13#10 +
    '            this.intervalId = null;' + #13#10 +
    '        }' + #13#10 +
    '    },' + #13#10 +
    '    checkForElements: function() {' + #13#10 +
    '        var loadingElement =document.querySelector(''.button.is-success.is-loading'');' + #13#10 +
    '        var audioElement = document.querySelector(''audio'');' + #13#10 +
    '' + #13#10 +
    '        if (loadingElement) {' + #13#10 +
    '            sharedController.sendMessage(''[LOADING]'');' + #13#10 +
    '        } else if (audioElement) {' + #13#10 +
    '            if (!audioElement.paused) {' + #13#10 +
    '                sharedController.sendMessage(''[SPEAKING]'');' + #13#10 +
    '            } else {' + #13#10 +
    '                sharedController.sendMessage(''[READY]'');' + #13#10 +
    '            }' + #13#10 +
    '        }' + #13#10 +
    '    }' + #13#10 +
    '};' + #13#10 +
    '' + #13#10 +
    'intervalController.start();';


      if Assigned(WVBrowser1) then  WVBrowser1.ExecuteScript(js);
end;

//------------------------------------------------------------------------------
// Form Create

procedure TForm3.FormCreate(Sender: TObject);
begin
IsSplitting := False;
TTSMaxLength := 250;
RealNamesList := Tstringlist.Create();
ListofThingsToSay := Tstringlist.Create();
ServiceList := Tstringlist.Create();
CharLimitList := Tstringlist.Create();
Memo1.Text:='';
Form3.ReallyShow:=False;
 DialogueShown:=False;
 LoadingVoiceTimeOut:=0;
 GotVoiceList := False;
end;

//------------------------------------------------------------------------------
// Form Show

procedure TForm3.FormShow(Sender: TObject);

  begin

    if Not Form3.ReallyShow then
  begin
    form3.Top := Form1.Top;
    form3.Left := Form1.Left;
    Self.BorderStyle := bsNone;
    form3.Height :=10;
    form3.Width :=10;
    Application.ProcessMessages;
    Form3.Update;
  end;

   // Load The Browser
  if GlobalWebView2Loader.InitializationError then
    showmessage(GlobalWebView2Loader.ErrorMessage)
    else
    if GlobalWebView2Loader.Initialized then
    begin
    WVBrowser1.CreateBrowser(WVWindowParent1.Handle) ;
    end
    else
    Timer1.Enabled := True;
    end;

//------------------------------------------------------------------------------
// Load The Browser Timer

procedure TForm3.Timer1Timer(Sender: TObject);
begin
  Timer1.Enabled := False;
  if GlobalWebView2Loader.Initialized then
  WVBrowser1.CreateBrowser(WVWindowParent1.Handle)
  else
  Timer1.Enabled := True;
end;

//------------------------------------------------------------------------------
// Voice Load Time Out Show Dialogue asking whether to Cancel Ignore or Try Again

procedure TForm3.Timer2Timer(Sender: TObject);
var  UserResponse:integer;
begin
  Timer2.Enabled:=False;
  WVBrowser1.ExecuteScript('intervalController.stop();');
  if DialogueShown then exit;

  DialogueShown:=True;
  LoadingVoiceTimeOut:=0;

  // Show the dialog with custom message and buttons
  UserResponse := MessageDlg('There was an error generating the voice.' + #13#10 +
  'Select:' + #13#10 +
  'Cancel to select a different voice and retry' + #13#10 +
  'Retry to try again with the same voice' , mtWarning, [mbRetry, mbCancel], 0);

  // Handle the user response
  case UserResponse of
  mrRetry:

  begin
  DialogueShown := False;
  Form1.TTStatus := '[READY]';
  Speak(Retry);
  end;

  mrCancel:

  Begin
  //  ShowMessage('You chose to cancel.');
  DialogueShown := False;
  Form1.Button3.Visible:=True;
  exit;
  End;

 end;

 end;

//------------------------------------------------------------------------------
// Prevents SplitStringIntoSections being interrputed By AI Responding With Summerization of webpage text

procedure TForm3.Timer3Timer(Sender: TObject);

begin
Timer3.Enabled := False;
if Not IsSplitting then
begin
  SplitStringIntoSections(NextStringToSplit,TTSMaxLength,ListOfThingsToSay);
Exit;
end;
Timer3.Enabled := True;
end;

//------------------------------------------------------------------------------
// Web Browser
//------------------------------------------------------------------------------
procedure TForm3.WMMove(var aMessage : TWMMove);
begin
  inherited;
  if (WVBrowser1 <> nil) then
  WVBrowser1.NotifyParentWindowPositionChanged;
end;

//------------------------------------------------------------------------------

procedure TForm3.WMMoving(var aMessage : TMessage);
begin
  inherited;
  if (WVBrowser1 <> nil) then
  WVBrowser1.NotifyParentWindowPositionChanged;
end;

 //-----------------------------------------------------------------------------

 procedure TForm3.WVBrowser1AfterCreated(Sender: TObject);
begin
  WVWindowParent1.UpdateSize;
  WVBrowser1.Navigate('https://lazypy.ro/tts/?lang=All&g=A');
  WVWindowParent1.UpdateSize;
end;

//------------------------------------------------------------------------------

initialization
  GlobalWebView2Loader := TWVLoader.Create(nil);
  GlobalWebView2Loader.UserDataFolder := ExtractFileDir(Application.ExeName) + '\CustomCache';
  GlobalWebView2Loader.StartWebView2;
end.
